import src from "./src.data";

export default [
  {
    id: "preface",
    title: "Preface",
    number: null,
    type: "header",
    prefix: null,
    link: src.TestPDF,
    children: null,
  },
  {
    id: "core-material",
    title: "Core Material",
    number: null,
    type: "header",
    prefix: null,
    link: "",
    children: [
      {
        id: "linear-regression",
        title: "Linear Regression in Moderately High Dimensions",
        number: 1,
        type: "item",
        prefix: ["Predictive Inference", "1"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "randomized-experiments",
        title: "Randomized Experiments",
        number: 2,
        type: "item",
        prefix: ["Causal Inference", "1"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "high-dimensional-linear-regression",
        title: "Modern High Dimensional Linear Regression",
        number: 3,
        type: "item",
        prefix: ["Predictive Inference", "2A"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "causal-identification",
        title: "Causal Identification via Conditional Exogeneity",
        number: 4,
        type: "item",
        prefix: ["Causal Inference", "2A"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "inference-on-predictive-and-causal-effects",
        title:
          "Inference on Predictive and Causal Effects in High Dimensional Linear Regression Models",
        number: 5,
        type: "item",
        prefix: ["Predictive Inference", "2B"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "structural-equations",
        title: "Structural Equations and Conditional Exogeneity",
        number: 6,
        type: "item",
        prefix: ["Causal Inference", "2B"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "high-dimensional-nonlinear-regression",
        title: "Modern High Dimensional Nonlinear Regression",
        number: 7,
        type: "item",
        prefix: ["Predictive Inference", "3"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "causal-dags",
        title: "Causal DAGs, Markov Nets, Nonlinear SEMs",
        number: 8,
        type: "item",
        prefix: ["Causal Inference", "3"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "debaised-ml-inference",
        title:
          "Debiased ML Inference on Predictive and Causal Effects in Modern Nonlinear Regression Models",
        number: 9,
        type: "item",
        prefix: ["Predictive Inference", "4"],
        link: src.TestPDF,
        children: null,
      },
      {
        id: "deep-learning",
        title:
          "Feature Engineering With Deep Learning for Causal and Predictive Inference",
        number: 10,
        type: "item",
        prefix: ["Predictive Inference", "5"],
        link: src.TestPDF,
        children: null,
      },
    ],
  },
  {
    id: "advanced-core-material",
    title: "Advanced Core Material",
    number: null,
    type: "header",
    prefix: null,
    link: "",
    children: [
      {
        id: "unobserved-confounders",
        title:
          "Unobserved Confounders, Instrumental Variables, and Proxy Controls",
        number: 11,
        type: "item",
        prefix: null,
        link: src.TestPDF,
        children: null,
      },
      {
        id: "debaised-ml-for-iv",
        title:
          "Debiased ML for IV and Proxy Controls Models and Robust DML Inference under Weak Identification",
        number: 12,
        type: "item",
        prefix: null,
        link: src.TestPDF,
        children: null,
      },
    ],
  },
  {
    id: "topics",
    title: "Topics",
    number: null,
    type: "header",
    prefix: null,
    link: "",
    children: [
      {
        id: "inference-on-heterogeneous-treatment-effects",
        title: "Inference on Heterogeneous Treatment Effects",
        number: 13,
        type: "item",
        prefix: null,
        link: src.TestPDF,
        children: null,
      },
    ],
  },
];
